parameters:
    crowd_reactive_cloud_resizer.service.class: CrowdReactive\CloudResizerBundle\Services\CloudResizer
    crowd_reactive_cloud_resizer.twig_extension.class: CrowdReactive\CloudResizerBundle\Twig\CloudResizerExtension
    crowd_reactive_cloud_resizer.provider.cloudimage.class: CrowdReactive\CloudResizerBundle\CloudResizer\Provider\CloudImage

services:
    crowd_reactive_cloud_resizer.service:
        class: %crowd_reactive_cloud_resizer.service.class%
        arguments: []

    crowd_reactive_cloud_resizer.twig_extension:
        class: %crowd_reactive_cloud_resizer.twig_extension.class%
        arguments: [ @crowd_reactive_cloud_resizer.service ]
        tags:
            - { name: twig.extension }
