parameters:
    crowdreactive_cloudresizer.service.class: CrowdReactive\CloudResizerBundle\Services\CloudResizer
    crowdreactive_cloudresizer.twig_extension.class: CrowdReactive\CloudResizerBundle\Twig\CloudResizerExtension

services:
    crowdreactive_cloudresizer.service:
        class: %crowdreactive_cloudresizer.service.class%
        arguments: []

    crowdreactive_cloudresizer.twig_extension:
        class: %crowdreactive_cloudresizer.twig_extension.class%
        arguments: [ @crowdreactive_cloudresizer.service ]
        tags:
            - { name: twig.extension }
