parameters:
    crowdreactive_image_filter.service.class: CrowdReactive\ImageFilterBundle\Services\ImageFilter
    crowdreactive_image_filter.twig_extension.class: CrowdReactive\ImageFilterBundle\Twig\FilterExtension

services:
    crowdreactive_image_filter.service:
        class: %crowdreactive_image_filter.service.class%
        arguments: []

    crowdreactive_image_filter.twig_extension:
        class: %crowdreactive_image_filter.twig_extension.class%
        arguments: [ @crowdreactive_image_filter.service ]
        tags:
            - { name: twig.extension }
